apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: k8spark
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: "us-south1-docker.pkg.dev/datademo06-443221/datademorepo/myk8spark"
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - resources/abnb.yaml
